## =========================
## Circleator config: 4.5 Mb bacterial genome
## =========================
## "Genes": "#4daf4a", # medium green
## "tRNAs": "#984ea3", # purple
## "rRNAs": "#e41a1c", # red
## "Illumina Coverage": "#3aa0d5", # blue
    
coords outerf=1.07,tick-interval=50000,label-interval=250000,label-units=kb,label-precision=0

small-cgap

## Forward strand
genes-fwd  heightf=0.05,color1=#4daf4a
tRNAs-fwd  heightf=0.05,innerf=same,color1=#984ea3
rRNAs-fwd  heightf=0.05,innerf=same,color1=#e41a1c

tiny-cgap

## Reverse strand
genes-rev  heightf=0.05,color1=#4daf4a
tRNAs-rev  heightf=0.05,innerf=same,color1=#984ea3
rRNAs-rev  heightf=0.05,innerf=same,color1=#e41a1c

small-cgap
new cov graph 0.14 graph-function=BAMCoverage,bam-file=FinalAssembly_Bactopia.backmap.sorted.bam,bam-seqid=FinalAssembly_Bactopia,graph-min=0,graph-max=data_max,window-size=5000,heightf=0.25,opacity=0.85,color1=#3aa0d5
